[package]
name = "sona"
version = "0.1.0"
edition = "2021"

[dependencies]
bzip2 = "0.4.4"
directories = "5.0.1"
rand = "0.8.5"
ratatui = "0.28.1"
serde = { version = "1.0.210", features = ["derive"] }
toml = "0.8.19"
